name: waygo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  http: ^1.1.0

  # Google Maps packages
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.14+2

  # Location and permissions
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # Internationalization
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assest/splash.jpg
    - assest/images1.jpg
    - assest/logo.png
    - assest/images2.jpg
    - assest/images3.jpg
    - assest/images4.jpg
    - assest/images5.webp
    - assest/images6.jpg
    - assest/banner.jpg
    - assest/eticket.jpg
    - assest/live_location.jpg
    - assest/main_news.jpg
    - assest/schedule.jpg
    - assest/seat_reserve.jpg
    - assest/ticket_price.jpg
