name: waygo
description: "A real-time bus tracking Flutter app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2

  cupertino_icons: ^1.0.2
  flutter_polyline_points: 3.1.0
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.14+2
  location: ^5.0.0
  flutter_svg: ^1.1.0

  # ğŸ“ Location & Permissions
  geolocator: ^14.0.2
  flutter_background: ^1.2.0
  permission_handler: ^12.0.1

  # ğŸ”Œ Realtime communication
  socket_io_client: ^3.1.2

  # ğŸŒ HTTP requests
  http: ^1.1.0
 

  # âœï¸ Fonts & UI
  google_fonts: ^6.3.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assest/splash.jpg
    - assest/images1.jpg
    - assest/logo.png
    - assest/images2.jpg
    - assest/images3.jpg
    - assest/images4.jpg
    - assest/images5.webp
    - assest/images6.jpg
    - assest/banner.jpg
    - assest/eticket.jpg
    - assest/live_location.jpg
    - assest/main_news.jpg
    - assest/schedule.jpg
    - assest/seat_reserve.jpg
    - assest/ticket_price.jpg
    